### ISSUE TITLE
SECRET_KEY leak

### ISSUE THREAD

**Issue by rohit-dua** [sethfitz/fireeagle-tutorial#1]
Hey, you have a secret key leaking in https://github.com/mojodna/fireeagle-tutorial/blob/master/python/settings.py#L4. Might wanna have a look.

**Comment by SteveMarshall** [comment]
Thanks @rohit-dua! If memory serves, that secret key pair was for an intentionally-created sample account.

That said, Fireeagle, the service this tutorial code documents [was closed by Yahoo! in February 2013](https://en.wikipedia.org/wiki/Fire_Eagle), so these secrets are for a service that no longer exists and thus don't present a problem so far as I can see?
